# Generated by Django 3.2.5 on 2021-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_api', '0002_alter_transactionmodel_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
