# Generated by Django 3.2.5 on 2021-07-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_api', '0003_transactionmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='parent_id',
        ),
        migrations.CreateModel(
            name='TransactionParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='transactions_api.transactionmodel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txn', to='transactions_api.transactionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='parents',
            field=models.ManyToManyField(related_name='_transactions_api_transactionmodel_parents_+', through='transactions_api.TransactionParentRelationship', to='transactions_api.TransactionModel'),
        ),
    ]
